import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Header from "../components/about/Header";
import WhatHero from "../components/about/WhatHero";
import MissionHero from "../components/about/MissionHero";
import Team from "../components/about/Team";
import CTA from "../components/about/CTA";

const About = () => {
  return (
    <>
      <div className=" bg-home-bkg bg-cover">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Header />
        <WhatHero />
        <MissionHero />
        <Team />
        <CTA />
        <Footer />
      </div>
    </>
  );
};

export default About;
