import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Blogs from "../components/Blogs";
import Newsletter from "../components/Newsletter";

const Blog = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Blogs />
      <Newsletter />
      <Footer />
    </>
  );
};

export default Blog;
