import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Hero from "../components/home/Hero";
import CryptoQueens from "../components/home/CryptoQueens";
import Product from "../components/home/Product";
import Mission from "../components/home/Mission";
import Partners from "../components/home/Partners";
import Blogs from "../components/Blogs";
import Newsletter from "../components/Newsletter";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <CryptoQueens />
      <Product />
      <Mission />
      <Partners />
      <Newsletter />
      <Blogs />
      <Footer />
    </div>
  );
}
