import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/product/Hero";
import SubHeader from "../components/product/SubHeader";
import Benefit from "../components/product/Benefit";
import FAQs from "../components/FAQ";

import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <SubHeader />
      <Benefit />
      <FAQs />
      <Footer />
    </div>
  );
}
