name: Deploy to production 🚀

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup NodeJS 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          yarn build && yarn next export && touch out/.nojekyll

      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: out
        env:
          fqdn: trycrypto.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
